In [1]:
import numpy as np;

In [3]:
x=np.random.rand(4);
print(x);

[0.38279781 0.43853436 0.59688622 0.55541227]


In [6]:
y = np.random.random(size=(4,5));
print(y);

[[0.30702531 0.14070019 0.36158579 0.544963   0.04338073]
 [0.44946982 0.59435505 0.08043143 0.34873434 0.36713155]
 [0.74813161 0.98857302 0.03164962 0.21202354 0.2873939 ]
 [0.08782272 0.50537121 0.14178413 0.40320257 0.65965758]]


In [7]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])